apiVersion: v1
kind: Namespace
metadata:
  name: teleport
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teleport-oidc
  namespace: teleport
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: teleport-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: secret/resilience-lab/teleport
        property: oidc-client-id
    - secretKey: client-secret
      remoteRef:
        key: secret/resilience-lab/teleport
        property: oidc-client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teleport-session-recording
  namespace: teleport
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: teleport-session-recording
    creationPolicy: Owner
  data:
    - secretKey: access-key
      remoteRef:
        key: secret/resilience-lab/teleport
        property: session-recording-access-key
    - secretKey: secret-key
      remoteRef:
        key: secret/resilience-lab/teleport
        property: session-recording-secret-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teleport-join-token
  namespace: teleport
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: teleport-join-token
    creationPolicy: Owner
  data:
    - secretKey: join-token
      remoteRef:
        key: secret/resilience-lab/teleport
        property: join-token-truenas
