apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://git.madavigo.com/madavigo/Resilience-Lab.git
    targetRevision: HEAD
    path: apps/platform/tailscale-operator
    directory:
      include: "external-secret.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: "1.96.5"
    helm:
      values: |
        installCRDs: true
        operatorConfig:
          defaultTags:
            - "tag:k8s"
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-funnel
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://git.madavigo.com/madavigo/Resilience-Lab.git
    targetRevision: HEAD
    path: apps/platform/tailscale-operator
    directory:
      include: "funnel-service.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: teleport
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
