apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cdi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.madavigo.com/madavigo/Resilience-Lab.git
    targetRevision: main
    path: apps/platform/cdi/config
  destination:
    server: https://kubernetes.default.svc
    namespace: cdi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
