apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lab-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.10.70.0/24
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: opnsense
  namespace: metallb-system
spec:
  myASN: 64513
  peerASN: 64512
  peerAddress: 10.10.67.1
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: lab-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - lab-pool
