apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: airship-lab-rootdisk
  namespace: airship-lab
spec:
  source:
    http:
      url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
    storageClassName: ceph-block
