apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: airship-lab
  namespace: airship-lab
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: airship-lab
    spec:
      nodeSelector:
        node-role/storage: "true"
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        memory:
          guest: 8Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            cpu: "1"
            memory: 8Gi
          limits:
            cpu: "2"
            memory: 8Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: airship-lab-rootdisk
        - name: cloudinit
          cloudInitNoCloud:
            userDataSecretRef:
              name: airship-lab-cloudinit
            networkDataSecretRef:
              name: airship-lab-cloudinit
