apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-events
    targetRevision: 2.4.9
    helm:
      values: |
        configs:
          jetstream:
            versions:
              - version: latest
                natsImage: nats:latest
                metricsExporterImage: natsio/prometheus-nats-exporter:latest
                configReloaderImage: natsio/nats-server-config-reloader:latest
                startCommand: /nats-server
        controller:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
