apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-api-credentials
  namespace: democratic-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: truenas-api-credentials
    creationPolicy: Merge
    template:
      data:
        driver-config-file.yaml: |
          driver: freenas-api-nfs
          instance_id:
          httpConnection:
            protocol: https
            host: 10.10.67.170
            port: 443
            allowInsecure: true
            apiVersion: 2
            apiKey: "{{ .apiKey }}"
          zfs:
            datasetParentName: SATA1/k8s/volumes
            detachedSnapshotsDatasetParentName: SATA1/k8s/snapshots
            datasetEnableQuotas: true
            datasetEnableReservation: false
            datasetPermissionsMode: "0777"
            datasetPermissionsUser: 0
            datasetPermissionsGroup: 0
          nfs:
            shareHost: 10.10.67.170
            shareAlldirs: false
            shareAllowedHosts: []
            shareAllowedNetworks:
              - 10.10.67.0/24
            shareMaprootUser: root
            shareMaprootGroup: root
  data:
    - secretKey: apiKey
      remoteRef:
        key: secret/resilience-lab/truenas
        property: apiKey
