apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-runner-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitea-runner-secrets
    creationPolicy: Owner
  data:
    - secretKey: registration-token
      remoteRef:
        key: {{ .Values.vault.secretPath }}
        property: registration-token
