{{- if .Values.dind.storageClass }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-storage
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.dind.storageClass }}
  resources:
    requests:
      storage: {{ .Values.dind.storageSize }}
{{- end }}
