apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
  namespace: wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
        - name: wiki
          image: ghcr.io/requarks/wiki:2
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /wiki/data
            - name: config
              mountPath: /wiki/config.yml
              subPath: config.yml
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 90
            periodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wiki-data
        - name: config
          configMap:
            name: wiki-config
