apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-data
  namespace: wiki
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 5Gi
